### ISSUE TITLE
Feature: Deploy configurations

### ISSUE THREAD

**Issue by koyablue** [koyablue/eventuner#12]
### Type of feature

🚀 Feature

### Description

Do deploy configurations for production environment.

https://zenn.dev/monicle/articles/a3c153c8127eb9
https://www.prisma.io/docs/orm/prisma-client/deployment/serverless/deploy-to-vercel
https://github.com/prisma/deployment-example-vercel/blob/main/package.json

### Tasks

- [x] Create new DB for production in Supabase
- [x] Add deploy command
- [x] Configure Vercel
- [x] Add env variables to Vercel
  - [x] Add NEXT_PUBLIC_API_BASE_URL and NEXT_PUBLIC_APP_BASE_URL after deploy to Vercel (because app url will be named by Vercel automatically and the name is unpredictable since we don't use our own custom domain)
