### ISSUE TITLE
Feature: Implement APIs

### ISSUE THREAD

**Issue by koyablue** [koyablue/eventuner#2]
### Type of feature

🚀 Feature

### Description

Implement the minimum APIs currently required.

API:
- POST: /api/events
  - Create a new event
- GET: /api/events/[uuid]
  - Get the event by uuid
- PATCH: /api/events/[id]
  - Update event by id
- DELETE: /api/events/[id]
  - Delete event by id
- POST: /api/events/[uuid]/attendances
  - Create attendance data

### Tasks

- [x] Implement POST: /api/events
- [x] Implement GET: /api/events/[uuid]
- [x] Implement POST: /api/events/[uuid]/attendances
- [x] Implement PATCH: /api/events/[id]
- [x] Implement DELETE: /api/events/[id]
