### ISSUE TITLE
Feature: Event detail page

### ISSUE THREAD

**Issue by koyablue** [koyablue/eventuner#9]
### Type of feature

🚀 Feature

### Description

Implement event detail page.
This page has:
- event name
- Attendance form

### Tasks

- [x] Implement event detail page UI
- [x] Implement attendance form
- [x] Implement GET: api/event/uuid/[uuid] API call
  - the endpoint should be api/event/u/[uuid] 
- [x] Fix create attendance API
  - [x] Change endpoint. /api/events/u/[uuid]/attendances -> /api/events/[id]/attendances
